version: "3.9"
   
services:

  redis:
    image: redis
    restart: always


  web:
    restart: always
    build: .
    volumes:
     - .:/code/
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"

  celery:
    build:
      context: .
    command: "celery -A task_2 worker -l info "
    restart: always
    volumes:
     - .:/code/ 

  celery-beat:
    build:
      context: .
    command: 'celery -A task_2 beat -l info'
    restart: always
    volumes:
     - .:/code/ 
