# Generated by Django 4.1.4 on 2022-12-09 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(max_length=10, verbose_name='Серия карты')),
                ('number', models.CharField(max_length=10, verbose_name='Номер карты')),
                ('balans', models.CharField(max_length=10, verbose_name='Баланс карты')),
                ('release', models.DateTimeField(verbose_name='Дата и время выпуска карты')),
                ('date_of_use', models.DateTimeField(verbose_name='Дата и время последнего использования карты')),
                ('end_of_activity', models.DateTimeField(verbose_name='Дата и время окончания активности карты')),
                ('status', models.CharField(choices=[('AC', 'activated'), ('NA', 'not activated'), ('EX', 'expired')], default='NA', max_length=2, verbose_name='Статус карты')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.CharField(max_length=10, verbose_name='Сумма списания с карты')),
                ('date', models.DateTimeField(verbose_name='Дата и время списания')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cardsmanager.card')),
            ],
        ),
    ]
