# Generated by Django 4.1.4 on 2022-12-10 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardsmanager', '0003_alter_card_release'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='number',
            field=models.CharField(max_length=12, verbose_name='Номер карты'),
        ),
        migrations.AlterField(
            model_name='card',
            name='series',
            field=models.CharField(max_length=4, verbose_name='Серия карты'),
        ),
    ]
