# Generated by Django 4.1.4 on 2022-12-10 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardsmanager', '0004_alter_card_number_alter_card_series'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='date_of_use',
            field=models.DateTimeField(editable=False, null=True, verbose_name='Дата и время последнего использования карты'),
        ),
    ]
