# Generated by Django 4.1.4 on 2022-12-10 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardsmanager', '0005_alter_card_date_of_use'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='release',
            field=models.DateTimeField(verbose_name='Дата и время выпуска карты'),
        ),
    ]
